### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by menro** [mafiuss/atom-cli-diff#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-cli-diff](https://github.com/mafiuss/atom-cli-diff) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getItem' of undefined

```
At /Users/Robert/.atom/packages/atom-cli-diff/lib/diff.coffee:27

TypeError: Cannot read property 'getItem' of undefined
  at Object.module.exports.selected (/Users/Robert/.atom/packages/atom-cli-diff/lib/diff.coffee:27:50)
  at atom-workspace.<anonymous> (/Users/Robert/.atom/packages/atom-cli-diff/lib/diff.coffee:9:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -4:10.9 core:paste (atom-text-editor.editor)
     -3:48.5 beautify:beautify-editor (atom-text-editor.editor)
     -3:31.0 editor:toggle-soft-wrap (atom-text-editor.editor)
     -2:46.1 application:new-file (atom-text-editor.editor)
     -2:44.7 core:paste (atom-text-editor.editor.is-focused)
     -2:38.8 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
     -2:17.0 git-diff:toggle-diff-list (atom-text-editor.editor.is-focused)
     -1:39.8 core:confirm (atom-text-editor.editor.mini)
     -0:44.4 window:focus-pane-on-right (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:32.0 diff:selected (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.0
atom-cli-diff, v0.11.0
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by smutnyleszek** [comment]
It was working few weeks ago. Today, out of curiosity, I tried diffing 4 files. Now I get the same error every time I try to use `Diff selected files` with 1, 2 and more files selected.

**Atom version**: 1.0.19
**Package version**: 1.1.0

**Comment by bogdanRada** [comment]
Is there any update on this? I don't see any comments since almost 2 years ago.

**Comment by jrial** [comment]
Was presumably fixed on Jan. 7, 2016, but I'm still getting it.

**Comment by mafiuss** [comment]
Hey jrial, can you elaborate please? I will look into it today

**Comment by jrial** [comment]
Sorry, didn't see your response until today.

There is not much to elaborate; I select 2 files in the tree, right click and select "Diff selected files". An error pops up, informing me that the issue is already reported and it redirects me to this issue.

The error report is as follows:

[Enter steps to reproduce:]

1. Select two files in the file tree
2. Right click on one of them
3. Select "Diff selected files"

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Linux Mint
**Thrown From**: [atom-cli-diff](https://github.com/mafiuss/atom-cli-diff) package 1.9.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getItem' of undefined

```
At /home/nighty/.atom/packages/atom-cli-diff/lib/diff.coffee:110

TypeError: Cannot read property 'getItem' of undefined
    at Object._selectedPaths (/packages/atom-cli-diff/lib/diff.coffee:110:30)
    at Object.selected (/packages/atom-cli-diff/lib/diff.coffee:43:22)
    at /packages/atom-cli-diff/lib/diff.coffee:13:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:56.1.0 diff:selected (span.name.icon.icon-file-text.am-active)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-cli-diff 1.9.0 
atom-django 0.3.2 
atom-meld 0.3.5 
atom-python-virtualenv 0.14.0 
atom-transpose 0.3.4 
autocomplete-python 1.9.1 
blame 0.12.0 
busy-signal 1.4.3 
custom-title 1.0.1 
data-atom 0.25.2 
DjangoRAD 0.0.1 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-watcher 1.1.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
hyperclick 0.1.2 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-django 0.1.1 
language-nginx 0.8.0 
linter 2.2.0 
linter-pycodestyle 2.0.2 
linter-pylint 2.1.0 
linter-ui-default 1.6.2 
local-history 4.3.0 
merge-conflicts 1.4.5 
minimap 4.28.3 
minimap-linter 2.0.1 
monokai 0.24.0 
open-html-in-browser 0.1.0 
open-terminal-here 2.3.1 
persistent-undo 1.2.0 
project-manager 3.3.5 
python-tools 0.6.9 
selection-highlight 0.1.6 
sort-lines 0.14.0 
symbols-tree-view 0.14.0 
tag 0.5.0 
termination 0.5.1 
up2date 0.1.2 
Zen 0.18.0 
```

**Comment by bhorrock** [comment]
The 33 month Bump.
