### ISSUE TITLE
Uncaught Error: wrong number of arguments for this command

### ISSUE THREAD

**Issue by t-hall** [mafiuss/atom-cli-diff#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-cli-diff](https://github.com/mafiuss/atom-cli-diff) package, v1.1.0

### Stack Trace

Uncaught Error: wrong number of arguments for this command

```
At /Users/thall/.atom/packages/atom-cli-diff/lib/diff.coffee:32

Error: wrong number of arguments for this command
  at Object.module.exports.selected (/Users/thall/.atom/packages/atom-cli-diff/lib/diff.coffee:32:17)
  at atom-workspace.<anonymous> (/Users/thall/.atom/packages/atom-cli-diff/lib/diff.coffee:9:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:18.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:18.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:13.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:13.6.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:10.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.3.0 diff:selected (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-cli-diff, v1.1.0
compare-files, v0.6.1
jsonpp, v0.0.10
line-diff-details, v1.1.1
minimap, v4.10.2
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by AlexMax** [comment]
Can also verify that I am getting this error message as well, with a similar stacktrace.  This happens when I try and diff using either "selected" or "clipboard".

**Comment by mico** [comment]
the same error when i clicked "selected"
