### ISSUE TITLE
Uncaught Error: Error

### ISSUE THREAD

**Issue by mzalimeni** [mafiuss/atom-cli-diff#15]
[Enter steps to reproduce below:]

1. Attempt to diff two Java code snippets using Current File v. Clipboard option

May be due to Java code being semi-interpretable as JS?

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-cli-diff](https://github.com/mafiuss/atom-cli-diff) package, v1.1.0

### Stack Trace

Uncaught Error: Error

```
At /Users/michael.zalimeni/.atom/packages/atom-cli-diff/lib/diff.coffee:59

Error: Error
  at Object.module.exports.clipboard (/Users/michael.zalimeni/.atom/packages/atom-cli-diff/lib/diff.coffee:59:17)
  at atom-workspace.<anonymous> (/Users/michael.zalimeni/.atom/packages/atom-cli-diff/lib/diff.coffee:10:63)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:20.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:17.1.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:12.6.0 core:cut (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:11.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.7.0 diff:clipboard (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.1.0
regex-railroad-diagram, v0.8.0

# Dev
No dev packages
```

**Comment by davej** [comment]
Also got this error.

**Comment by mafiuss** [comment]
can you paste your sinppets so I can run the test @mzalimeni ? same for you @davej I will pus an update in a bit let me know if that fixed things

**Comment by davej** [comment]
Sorry this was a few weeks ago and I don't recall what I was doing. If it happens again then I'll post the details here.

**Comment by mzalimeni** [comment]
Same here, unfortunately I can't remember either. Will do the same as @davej, @mafiuss
