### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mloncaric** [mafiuss/atom-cli-diff#7]
[Enter steps to reproduce below:]

1. Select two random files
2. Right click on one and select "Diff selected files"

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-cli-diff](https://github.com/mafiuss/atom-cli-diff) package, v0.8.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/Miran/.atom/packages/atom-cli-diff/lib/helpers/diff-helper.coffee:6

TypeError: undefined is not a function
  at DiffHelper.module.exports.DiffHelper.selectedFiles (/Users/Miran/.atom/packages/atom-cli-diff/lib/helpers/diff-helper.coffee:6:5)
  at Object.module.exports.selected (/Users/Miran/.atom/packages/atom-cli-diff/lib/diff.coffee:26:25)
  at atom-workspace.<anonymous> (/Users/Miran/.atom/packages/atom-cli-diff/lib/diff.coffee:9:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:141:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -1:17.3 core:move-right (atom-text-editor.editor)
     -1:12.6 core:backspace (atom-text-editor.editor)
     -1:11.5 core:delete (atom-text-editor.editor)
     -1:11.2 core:paste (atom-text-editor.editor)
     -1:03.7 core:copy (atom-text-editor.editor)
     -0:52.1 core:backspace (atom-text-editor.editor)
     -0:51.3 core:paste (atom-text-editor.editor)
     -0:40.7 core:copy (atom-text-editor.editor)
     -0:38.3 core:paste (atom-text-editor.editor)
     -0:31.6 core:move-right (atom-text-editor.editor)
     -0:31.2 editor:delete-to-beginning-of-line (atom-text-editor.editor)
     -0:30.9 core:backspace (atom-text-editor.editor)
     -0:30.4 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -0:30.0 editor:delete-to-beginning-of-line (atom-text-editor.editor)
     -0:29.7 core:backspace (atom-text-editor.editor)
  2x -0:28.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "atom-jshint"
    ],
    "themes": [
      "neutron-ui",
      "neutron-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.2
atom-cli-diff, v0.8.0
emmet, v2.3.3
git-plus, v4.4.1
language-latex, v0.4.1
meteor-api, v2.12.0
neutron-syntax, v0.6.2
neutron-ui, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by mafiuss** [comment]
Thanks, I'll look into it, I wonder, is your project drawer panel on the left or right?

**Comment by mloncaric** [comment]
It's on the left.

**Comment by mafiuss** [comment]
Can you check if this was fixed in the latest version? Thank you
